name = "telegram-worker"
main = "worker/index.js"
compatibility_date = "2024-05-01"
account_id = "your id"
type = "javascript"

[vars]
TELEGRAM_TOKEN = "your token"

[[kv_namespaces]]
binding = "FILES"
id = "your id"
