name = "telegram-worker"
main = "worker/index.js"
compatibility_date = "2024-05-01"
account_id = "5c2be7ac942e2e75bac1932ff430469c"
type = "javascript"

[vars]
TELEGRAM_TOKEN = "7612321475:AAFDqNJSrXZaqXZXrftVVXfMFpSjOhtu3eY"

[[kv_namespaces]]
binding = "FILES"
id = "e788910637d74e08aaa18e45fd96dbcf"
