name = "telegram-worker"
main = "worker/index.js"
compatibility_date = "2024-05-01"

[vars]
TELEGRAM_TOKEN = "7612321475:AAFDqNJSrXZaqXZXrftVVXfMFpSjOhtu3eY"

[[kv_namespaces]]
binding = "FILES"
id = "e788910637d74e08aaa18e45fd96dbcf"
